### ISSUE TITLE
Live view of changes via read-only shared link

### ISSUE THREAD

**Issue by damianbulira** [ONLYOFFICE/onlyoffice-nextcloud#1051]
My main point in using OnlyOffice in OwnCloud was sharing folders publicly with password protection so the audience can see document changes via read-only links live as the content is created. Therefore I was thrilled to see this being implemented: https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/143

However, once the editor is making changes to the document, only other editors can see it live. Users with view-only permissions don't have it refreshed. Even refreshing the page doesn't help. I found out that when the editor closes the file (not only saves it) and the viewer refreshes the page, then the changes are reflected. It might be related to the similar issue with OwnCloud: https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/488

OnlyOffice Document Server version: 8.2.2 (exactly Ubunutu 22.04 8.2.2-22)
OnlyOffice Nextcloud connector version: 9.5.0
Nextcloud Hub 9 (30.0.4)

**Comment by SergeyKorneyev** [comment]
Hello,
The live viewer functionality (https://api.onlyoffice.com/docs/docs-api/get-started/how-it-works/viewing/) in the Nextcloud integration is implemented in such a way that it's only available for users that are signed in. Anonymous (external) users can only access the regular viewing mode. It's designed this way since the number of live view connections is determined by the license and regular viewing connections are unlimited.
