### ISSUE TITLE
Make https communication between Nextcloud and Onlyoffice optional

### ISSUE THREAD

**Issue by ejgutierrez74** [ONLYOFFICE/onlyoffice-nextcloud#167]
Dont know if its possible with some setting as securecommunication true or false.
Im trying to use DocumentServer and onlyoffice in local machine with educational purpose, but it adds many complexity to secure the connection, using for example letsencrypt or openssl. This difficults the config and in my case they dont bring any new feature.

So would be nice, that people not interested, or perhpaps to test if it works, use only http, and then if its works and they need to secure, theyd advance and make it secure through https

I must add that i think collabora online has similar option when launching docker, you can add a parameter similar to "ssl-enabled: true or false".

Thanks for your work

**Comment by alexanderonlyoffice** [comment]
@ejgutierrez74, enabling of HTTPS is not obligatory. The main thing is that if you use HTTPS on Nextcloud side, the Document Server also requires HTTPS to make the integration work. Otherwise there will be a lack of security on one side of the integration and the integration won't work this way. 

There are several options, you can choose to secure the connection between Nextcloud and Document Server: 

1. The first one is JWT. You may find more information about JWT in our API documentation [here](https://api.onlyoffice.com/editors/security). 
2. The second option is to restrict access to the Document Server using ipfilter. You can find this parameter in /etc/onlyoffice/documentserver/default.json. If you are using Docker installation, default.json will be in the container with the Document Server. Please do not forget to restart all services of the Document Server with `supervisorctl restart all`, if you make any changes to the configuration files.
```
"ipfilter": {
           "rules": [{"address": "*", "allowed": true}],
           "useforrequest": false,
           "errorcode": 401
```
You can type in the ip address or a domain name.
