### ISSUE TITLE
Change standard template

### ISSUE THREAD

**Issue by DaBozzz** [ONLYOFFICE/onlyoffice-nextcloud#173]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
The default template uses Arial as the font. I want to be able to change the default font to Calibri and change the default language as well. Can this be done?

**DocumentServer version:**
5.4.2

**Operating System:**
Ubuntu 18.04 LTS

**Browser version:**
Chrome 79

Thank you for your help!

**Comment by alexanderonlyoffice** [comment]
@DaBozzz, the default language is being chosen depending on the user's language from this list. If you want to change them, you need to replace them in the application.

**Comment by DaBozzz** [comment]
Replacing the files in the asset folder does the trick, thanks!

**Comment by awesome-manuel** [comment]
@LinneyS could this feature be added to the Nextcloud plugin?

**Comment by alexanderonlyoffice** [comment]
@awesome-manuel, could you please describe the usage scenario of the requested feature, i.e. how do you see this feature looks like? We would appreciate getting your feedback on that.

**Comment by awesome-manuel** [comment]
@alexanderonlyoffice right now the workaround is to modify the files named `new.*` that are included in the addon. But then Nextcloud complains about modified files.

My suggestion is to add a setting that allows to define a path for each template file. Since only admins can change this settings it could be either a path to a file inside the Nextcloud namespace (that can be modified using the online editors) or a path on the server, where the admin stores some custom templates.

**Comment by alexanderonlyoffice** [comment]
@awesome-manuel, thank you very much for your feedback. Our Design Department is considering the way this feature will be implemented at the moment and we are planning to release it within one of the next versions of the connector. Unfortunately, I cannot tell you any time frames at the moment.
