### ISSUE TITLE
HTTPS address for Document Server is required

### ISSUE THREAD

**Issue by arathink** [ONLYOFFICE/onlyoffice-nextcloud#177]
Error when trying to connect (Mixed Active Content is not allowed. HTTPS address for Document Server is required.)

**Comment by alexanderonlyoffice** [comment]
@arathink, please note that if your Nextcloud uses HTTPS, Document Server also must use HTTPS, otherwise you will get the mixed content error. Please follow this [link](https://helpcenter.onlyoffice.com/server/document.aspx) to find installation guides for the Document Server for all supported installation types, as well as instructions how to enable HTTPS.
