### ISSUE TITLE
Nextcloud 19 compatibility

### ISSUE THREAD

**Issue by ntimo** [ONLYOFFICE/onlyoffice-nextcloud#293]
### Steps to reproduce
1. Update to Nextcloud 19
2. Go to Settings --> Apps
3. The app is deactivated because it does not Support Nextcloud 19

### Expected behaviour
The app should support Nextcloud 19

### Actual behaviour
It only supports Nextcloud 18

### Server configuration
**Nextcloud version:** 19.0.0

**Where did you install Nextcloud from:**
self build nextcloud 19 docker image

**Comment by HLFH** [comment]
Fixed in this PR: https://github.com/ONLYOFFICE/onlyoffice-nextcloud/pull/294

**Comment by tufand** [comment]
Error when trying to connect (Host violates local access rules)✖

**Comment by jmlgo** [comment]
I'm experiencing the same issue: 
`Error when trying to connect (Host violates local access rules`

**Comment by jmlgo** [comment]
Solved adding this to config.php:

`'allow_local_remote_servers' => true,`

This was added in 19 update
https://github.com/nextcloud/server/blob/dba76c04bba910c3c6f1dec4f3eba6416ec3378d/lib/private/Http/Client/Client.php#L154

**Comment by HLFH** [comment]
> Error when trying to connect (Host violates local access rules)✖

Please read this issue: https://github.com/nextcloud/documentserver_community/issues/75 ; it might be related.

**Comment by HLFH** [comment]
New release compatible with NC 19. https://github.com/ONLYOFFICE/onlyoffice-nextcloud/releases/tag/v4.2.0 Close this issue?

**Comment by tufand** [comment]
> https://github.com/nextcloud/server/blob/dba76c04bba910c3c6f1dec4f3eba6416ec3378d/lib/private/Http/Client/Client.php#L154-158
> This was added in 19 update.
> 
> Solved adding this to config.php:
> 
> `'allow_local_remote_servers' => true,`

Thanks for comment. (y)

**Comment by niziak** [comment]
Or using OCC: `config:system:set allow_local_remote_servers --value true --type bool`

**Comment by ant0nwax** [comment]
Thanks for the comment with
'allow_local_remote_servers' => true,

i added this to 
/var/www/html/nextcloud/config/config.php
on the nextcolud server


@ShockwaveNN i made it until here and this is the solution for the issue
https://github.com/ONLYOFFICE/DocumentServer/issues/1659

i wonder if the documentation shall be adjusted on the Nextcloud AND on the ONLYOFFICE side
that is just my recommendation because I am not aware about how you guys integrate the two apps together
i would say because my construction is
- LOCAL nextcloud server subdomain1.domain1.tld1
- LOCAL onlyoffice server subdomain2.domain2.tld2
- LOCAL webserver reverse proxy who servers both domain1 and doain2 inside the same webserver :)

please treat me like a unexperienced webservices integrator :)
