### ISSUE TITLE
Saving bugged

### ISSUE THREAD

**Issue by FutureTecSystems** [ONLYOFFICE/onlyoffice-nextcloud#363]
Currently I'm using the following components:

NextCloud 19.0.3
OnlyOffice 6.0.0
Community Document Server 0.1.7

Becaus of the bug in closing of documents (https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/353) I've upgraded to 6.0.0.

Closing works basically but has the following effect: 

1) I change a line and close the editor
2) I open the document again
3) Line is empty and locked with my own user

Additionally the changes in file don't get synced to the client, File is empty.

IMHO this sounds like a problem with the "modified at" information

**Comment by FutureTecSystems** [comment]
Got another effect... if I'm saving a synced document in the local Nextcloud folder it gets overwritten immediately with the server version

**Comment by mhier** [comment]
After updating to the onlyoffice plugin 6.0.0, we lost the last two to three days of changes in one spreadsheet table which we edit once per day and user (8 users). Also the "Modified" column in Nextcloud itself says it would be last modified 2 days ago, despite we have just put in the missing entries (and they seem to stay). In "Activity" it says, 'Changed by "remote user" 8 days ago' as the most recent activity. In "Versions" it says, the latest version is from 5 days ago. This looks all quite inconsistent, although I have not checked this information recently.

**Comment by acsfer** [comment]
Here too, we've lost changes in Spreadsheet made the last 2 days, and one of the documents is now empty.
Is there any chance to recover these?

**Comment by LinneyS** [comment]
Updating the `Nextcloud ONLYOFFICE integration app` to version 6.0.0 could not affect the opening of previous saved files. And couldn't erase your files. The problem is that the files weren't saved before from Document Server.

Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).

**Comment by FutureTecSystems** [comment]
Why are you closing this issue?

Community Document Server 0.17
Nextcloud ONLYOFFICE integration app 4.3.0
--> Working

Community Document Server 0.17
Nextcloud ONLYOFFICE integration app 5.0.0
--> Not Working

Community Document Server 0.17
Nextcloud ONLYOFFICE integration app 6.0.0
--> Not Working

Easy way to blame others although the versions indicate a problem with the integration app

**Comment by LinneyS** [comment]
@FutureTecSystems 
As you can see: between the release of 4.3.0 and 5.0.0, there were no changes in file saving.
https://github.com/ONLYOFFICE/onlyoffice-nextcloud/pull/349/files#diff-78d880d68c67d3c700301210f9f9a438R371-R498
Saving history was added, but after saving the main file.

This app enables users to edit office documents from Nextcloud using ONLYOFFICE Document Server. Use of any other product is not included. And we do not guarantee correct work.

**Comment by FutureTecSystems** [comment]
Then maybe the wording "saving bugged" is not correct. Fact is that it's not working anymore after an update and this is not a small issue
