### ISSUE TITLE
Changes made to documents created in Onlyoffice are not saved correctly in Nextcloud

### ISSUE THREAD

**Issue by CB-IT-Chris** [ONLYOFFICE/onlyoffice-nextcloud#369]
**problem:**
Changes made to documents created in Onlyoffice are not saved correctly in Nextcloud. Synchronizing from Nextcloud Client to Onlyoffice will overwrite any changes made in Onlyoffice in a file. (data loss)

**Adjustable:**
Login in the Nextcloud and via the browser (Onlyoffice) create a new document, enter data and save it
Now open the just created document via the local PC and you can see that there is no content available.
If you now save or synchronize the document, everything in this document that was created in Onlyoffice will be overwritten.

**Environment:**
Nextcloud: 19.0.2
Community Document Server: 0.1.7
ONLYOFFICE: 5.0.0

**Comment by arnowelzel** [comment]
**I have the same problem and have to consider OnlyOffice Community Edition in Nextcloud as complete fail in it's current state! DO NOT USE! YOU WILL LOSE DATA!**

Our situation:

About 5 people spent many hours during about one week on editing on many documents for an upcoming private film festival. The fesitval has no big funding and people have to work from home due to the current situation with Corona. That's one of the reasons to use Nextcloud and the community edition of OnlyOffice. Now nearly **all** changes are only visible when opening the documents in OnlyOffice in the browser, but the changes did **not** get saved in the actual files! Nextcloud itself still thinks, the files are older than 5-7 days and when downloading the files, all changes are missing!

We discovered this by accident since I wondered, why people told us they already finished their work and the changes are not visible in the downloaded files. Somehow all the edits still are somewhere within the documentserver but never got written back to the actual files.

I use Nextcloud 19.0.3 and OnlyOffice 5.6.4 in a docker container and did not have any issue 12 months ago when we first tried this with older versions. But some of the last updates seemed to have introduced some very serious bugs.

The editor always "All changes saved" in the status bar but actually **nothing** was saved to the files at all.

Right now two people working on the tedious job to get all the content out of more than 50 documents with copy & paste out of the browser into a local editor running on the PC and we still don't know if all all changes are save then or not - and the deadline is in 4 days!

Yes, I know - it's open source and for free etc.. But nevertheless this must not happen! I am not a hobbyist with too much time - we are doing real work here!

When we hopefully got all our changes saved locally this was the last time I used OnlyOffice in Nextcloud ever. A software which jeopardizes the work of 5 people spending a week on getting things done can only be considered evil - sorry for the harsh words, but it's 1 AM in the night here at the moment and we have to spend time to get things fixed.

**Comment by ibnpetr** [comment]
@CB-IT-Chris @arnowelzel 
```
Environment:
Nextcloud: 19.0.2
ONLYOFFICE: 5.0.0
```
Could you please install [the latest version](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/master/CHANGELOG.md#600) of the connector and let us know if the issue still can be reproduced.
Please pay attention to the [Force Save](https://www.onlyoffice.com/blog/2020/09/onlyoffice-connector-v-6-0-0-for-nextcloud-with-force-save-is-available/) feature that allows you to save intermediate versions of the document when editing it.
Looking forward to hearing from you

**Comment by Galegod** [comment]
@CB-IT-Chris @arnowelzel

1 ONLYOFFICE has nothing to do with Community Documentserver. https://github.com/nextcloud/documentserver_community

2 Our product is available in our official repository only and has the name ONLYOFFICE Document Server.
https://github.com/ONLYOFFICE/DocumentServer
Here is our official connector https://github.com/ONLYOFFICE/onlyoffice-nextcloud

3 Please contact the author of the mentioned by you piece of code - the Nextcloud team who just took the AGPL v3 core of our software to add document editing to their platform not in the regular, well-tested and supported by our team way - via an integration app by ONLYOFFICE - but built-in directly generating a lot of troubles. Only Nextcloud can help with it now I'm afraid.

Sorry, but we are not ready to support the Community Documentserver as we see a lot of issues with it as well and never recommend it.

Please use our official open source software ONLYOFFICE, not the imitation created by other companies.

**Comment by arnowelzel** [comment]
To clarify the situation:

First of all: I am already in contact with OnlyOffice support - thanks for your active support!

About my setup: I use the Docker container, not the Community Documentserver. And I have never used the Community Documentserver ever.

The issues started somewhere in the last couple of weeks - I'm not sure if it was after updating Docker to onlyoffice/documentserver 5.6.4 or even earlier. At the time I noticed the issue I used the Docker version 5.6.4 and the Nextcloud integration app 6.0.0, however editing was done with an earlier version of the app as well, I just can't remember which version that was exactly.

The first thing which happend is that people told me that they get a message during editing sessions with spreadsheets that the document was changed and has to be reloaded. Sometimes this happend right after opening a document, sometimes during the editing session. In Chrome this happend less often as in Firefox.

This did not happen with documents, but for documents the changes did not get synced back to the file in Nextcloud but only stayed inside Docker - so you could open the document and see the changes inside the OnlyOffice editor but not in the file when downloading it.

I meanwhile updated the Docker container to the latest version which seems to be 5.6.5 and also activated the new option "Keep intermediate versions when editing" in the Nextcloud integration app as suggested in your article:

![grafik](https://user-images.githubusercontent.com/6613614/94274103-8f496680-ff45-11ea-9ee6-41ccaaaf6efa.png)

Some quick tests look promising - so far I could not reproduce the problems again. However I will do more thorough testing and let you know what the result is.

**Comment by ferdiga** [comment]
I had the same problem,
suddenly next to the cell appears a red field with my name with or without a prefix and all changes since opening the file are lost.

if "keep intermediate versions" could solve the problem at least for now it would be an easy fix - if this could be set as default

As long as it "works" as now it should be discourage to be used in production

**Comment by arnowelzel** [comment]
Just an update:

In spreadsheets I still have this error with "Internet connection has been restored" which comes very often about 1-2 minutes after the spreadsheet gets edited:

![grafik](https://user-images.githubusercontent.com/6613614/94336716-65e01780-ffe5-11ea-8c21-3cec9bdbbdc4.png)

After this message no further editing is possible, but at least the changes don't get lost.

I have another setup which runs the Docker version 5.6.0 and not 5.6.4 - and there this problem does not happen. I will try to downgrade the machine and see, if this changes anything.

**Comment by arnowelzel** [comment]
Ok, no change - even with 5.6.0 the error appears on that machine. So somehow the reliabiliy of the Docker version is affected by the environment it runs in.

The environment which seem to be OK with 5.6.0: Debian Linux 10 on a dedicated machine
The environment which has connection issues with 5.6.0 and 5.6.4: Ubuntu Linux 18.04 on a KVM based VM

I was courious: would the dedicated Debian server also work fine with the Nextcloud installation on the Ubuntu VM?

So I configured the Nextcloud integration app on the Ubuntu VM to use the Onlyoffice Docker version on the dedicated server. And the result: yes, it seems the version on the dedicated server just runs fine, also with the Nextcoud integration app on the VM.

However - using the dedicated server is not an option for me - the servers belong to different user groups and must not be mixed.

**Comment by arnowelzel** [comment]
I did another test: installing the Onlyoffice Documentserver as described in https://helpcenter.onlyoffice.com/de/server/linux/document/linux-installation.aspx

But again: **but no change there as well.**

What is this? Why does the document server always loses the connection? No other service on this machine ever had any issue at all. So it must be some weird problem inside the OnlyOffice Document server.

**Comment by arnowelzel** [comment]
This is the log about the incident in `/var/log/onlyoffice/documentserver/docservice` - at 14:27 was the moment, when the spreadsheet editor was showing the popup with the message "Internet connection has been restored...":

`[2020-09-26T14:24:37.474] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode
[2020-09-26T14:27:39.932] [WARN] nodeJS - error description: docId = 3739872172 errorId = Update Version error`

**Comment by ferdiga** [comment]
> I had the same problem,
> suddenly next to the cell appears a red field with my name with or without a prefix and all changes since opening the file are lost.
> 
> if "keep intermediate versions" could solve the problem at least for now it would be an easy fix - if this could be set as default
> 
> As long as it "works" as now it should be discourage to be used in production

Downside - the undo function is not available any more !!

**Comment by arnowelzel** [comment]
Another Update:

Meanwhile I've set up the OnlyOffice Documentserver on another complete new virtual server - 2 cores, 8 GB RAM, 160 GB storage. Besides OnlyOffice and Apache with Let's Encrypt as a proxy nothing else was installed.

But again the same pesky error in spreadsheets as soon as I start editing :-(.

Since there is one server one which is it seems to work (also using Apache as proxy), I can only assume there is some requirement which is only met by this single server.

Any suggestion is welcome.

**Comment by arnowelzel** [comment]
My problem is solved for me. It was caused by a misconfiguration of the Apache proxy (which had a ProxyTimeout setting - set once a long time ago to solve another issue and just forgout that :-( Mea culpa maxima).

Sorry for the fuss - but the Docker version works fine so far, you just have to confgure it correctly.

**Comment by ferdiga** [comment]
@arnowelzel , please could you post your correct apache config - or at least the crucial line which fixed your issue
thanks

**Comment by CB-IT-Chris** [comment]
My problem is still open. I will check it out tonight.

**Comment by ferdiga** [comment]
I get this - my name gass is prefixed with an internal code and from this point in time no editing is possible
![image](https://user-images.githubusercontent.com/6248560/94360470-ba4eca00-00ad-11eb-98f9-835a00f867df.png)

BTW I use the current App / Version Only iffice 6.0.0  and the community document server 0.1.7 supplied with nextcloud 19.0.3

**Comment by arnowelzel** [comment]
**First of all: the problems you described have nothing to do with ONLYOFFICE itself! You have to ask the team of Nextcloud to look into their implementation of the "Community Documentserver"!**

See here: https://github.com/nextcloud/documentserver_community

I don't use this app and never did. I only use the official Docker container which you can find here: https://hub.docker.com/r/onlyoffice/documentserver/ along with the official integration app: https://apps.nextcloud.com/apps/onlyoffice. The Docker container was set up with these commands on my Linux server:

```
docker pull onlyoffice/documentserver
docker run -i -t -d --name="onlyoffice" -p 127.0.0.1:8006:80 --restart=always -e JWT_ENABLED="true" -e JWT_SECRET="secret" onlyoffice/documentserver
```

Furthermore the relevant options in Apache to make this available via HTTPS:

```
SetEnvIf Host "^(.*)$" THE_HOST=$1
RequestHeader setifempty X-Forwarded-Proto https
RequestHeader setifempty X-Forwarded-Host %{THE_HOST}e
ProxyAddHeaders Off
ProxyPass /.well-known !
ProxyPassMatch (.*)(\/websocket)$ "ws://127.0.0.1:8006/$1$2"
ProxyPass / http://127.0.0.1:8006/
ProxyPassReverse / http://127.0.0.1:8006/
```

My mistake was the option `ProxyTimeout 10` which I added last year to solve another issue and which now caused lost connections. Since I removed that option everything works fine here.

But again: this is for the Docker version 5.6.5 and **not** the "Community Documentserver"!

**Comment by ferdiga** [comment]
Thanks
I thought the git channel
ONLYOFFICE / onlyoffice-nextcloud
is the right place to ask

**Comment by LinneyS** [comment]
@CB-IT-Chris @ferdiga 
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).

**Comment by LinneyS** [comment]
@arnowelzel  As I see your issue is not similar to the first message.
If the problem persists, please create a new issue
