### ISSUE TITLE
Missing close button

### ISSUE THREAD

**Issue by aproposnix** [ONLYOFFICE/onlyoffice-nextcloud#391]
Since the release of 6.1.0 there is no longer a way of closing the document other than navigate away from it (by cikcing on some other link or clicking back button). In the past you were able to click the 'X' to close it and then the user would be returned back to the folder where they selected the document. 

Can you please add this back?

Edit: I'm on NCv20

**Comment by stekaa** [comment]
If I see this correctly, it's not because of an update of onlyoffice-App but because of an update of documentserver. I am still running onlyoffice-App 6.0.0 and after updating documentserver to a newer version the close button has gone.

Instead there is now an folder-icon with an arrow (mouse over hint "open file location"). I am not sure if it was there already in former versions.  But it does the same as the former close button.

**Comment by aproposnix** [comment]
Yeah, that's an excellent workaround. Thank you. 

I think it's still advisable to make this more visible somehow. This is not intuitive at all.

**Comment by splitt3r** [comment]
I think this issue can be closed in favor of https://github.com/nextcloud/documentserver_community/issues/174.

**Comment by aproposnix** [comment]
Covered in #174

**Comment by Exist2Resist** [comment]
> I think this issue can be closed in favor of [nextcloud/documentserver_community#174](https://github.com/nextcloud/documentserver_community/issues/174).

No this does not work. Open File location does not close the active session of the document and keeps sessions open in memory. Session numbers grow with each subsequent opening of the document. This can potentially cause problems with memory and cache. 
Please reinstate the close button which terminates the session.

**Comment by GrenderG** [comment]
> > I think this issue can be closed in favor of [nextcloud/documentserver_community#174](https://github.com/nextcloud/documentserver_community/issues/174).
> 
> No this does not work. Open File location does not close the active session of the document and keeps sessions open in memory. Session numbers grow with each subsequent opening of the document. This can potentially cause problems with memory and cache.
> Please reinstate the close button which terminates the session.

Can confirm those problems are happening.

**Comment by sroesner** [comment]
Still the same problem with NEXTCLOUD v. 21. No "x" but the folder can be seen. The latter even gives this error:
<img width="660" alt="image" src="https://user-images.githubusercontent.com/44226749/133624198-128a3024-e677-4464-9d97-e6509a33d51b.png">

**Comment by ShockwaveNN** [comment]
@sroesner Please not that this issue was closed in favor on another issues

Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate [GitHub repository](https://github.com/nextcloud/documentserver_community). 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://forum.onlyoffice.com/t/community-document-server-app-in-nextcloud-18/268).
