### ISSUE TITLE
OnlyOffice opens documents in same tab regardless of setting...

### ISSUE THREAD

**Issue by samps** [ONLYOFFICE/onlyoffice-nextcloud#652]
After updating to 7.5.2 OnlyOffice opens all existing documents in the current tab. This happens regardless of the state of the "Open file in the same tab" option in Nextcloud settings for OnlyOffice.

This holds true for Nextcloud 24.0.1.1 on Ubuntu 22.04 Server on Linux 5.15.0-39, NGINX and PostGRESQL

**Comment by cheneraie** [comment]
Same for us in Nextcloud 22.2.9, Onlyoffice 7.4.2 and onlyoffice-documentserver 7.1.1-23

**Comment by kimselius** [comment]
Same issue here. 

Line 168 in main.js should be corrected to:
`         OCA.Onlyoffice.OpenEditor(fileId, context.dir, fileName, 0, (OCA.Onlyoffice.setting.sameTab ? document : null));`

The bug was introduced in this commit:
https://github.com/ONLYOFFICE/onlyoffice-nextcloud/commit/948c9f9f2da4adbdde92040444f3aebf410a9ed0

**Comment by ynott** [comment]
This bug is not a major one, but a very minor one. But, this is what frustrates me.

A quick fix would be greatly appreciated.
I have patched the Nextcloud at hand myself.
