### ISSUE TITLE
Force saving with revisions

### ISSUE THREAD

**Issue by natoponen** [ONLYOFFICE/onlyoffice-nextcloud#670]
Hello!

I'm using ONLYOFFICE 7.0.1.37 with Nextcloud 24.0.1.

I need to force save documents during co-edeting. When everyone leave co-edeting, file history stores revisions inside versions. But when I force save, there are no revisions in history.

**Expected behaviour**: Several users change file in co-edeting mode. Forcesave creates version with revisions in it.

**Current behaviour**: Several users change file in co-edeting mode. Forcesave creates version, but there are no revisions in it.

Is there any way to store revisions when forcesaving in co-edeting mode?

**Comment by SergeyKorneyev** [comment]
Hello,
Could you specify what exactly you mean by "revisions" in this case? We would also appreciate it if you provided some screenshots to demonstrate this.

**Comment by natoponen** [comment]
By "revisions" here I mean small versions inside a big one. As I understand they can be also called "changes". I'm wondering is it possible to have similarly looking version history for default save (when everyone leaves the editor) and for force save. In other words is it possible to have "changes" in versions made with force save?
![image](https://user-images.githubusercontent.com/57988162/193795892-e96b7769-7aef-4502-b1c9-7678bf9cbb8b.png)

**Comment by SergeyKorneyev** [comment]
Thanks for the clarification. 
I'm afraid that, due to the specifics of our editors, it's currently impossible to display the versions created with the force saving mechanism in the Version History menu. The ONLYOFFICE editors highlight the changes made from the beginning of the current editing session. However, in our current integration with Nextcloud, the editors cannot distinguish the original version of the document and another one created with force saving **_during_** the editing session, which is why the data from a force save is not stored in the version history.
