### ISSUE TITLE
Document download instead of opening in OnlyOffice

### ISSUE THREAD

**Issue by pierreozoux** [ONLYOFFICE/onlyoffice-nextcloud#713]
Hi,

we are facing a strange issue, and didn't manage to debug it fully.
It happens to some users, but not all. And I still don't understand why these users and not others.
And even for these users, it seems it is not all the time.
The worsts bugs to debug :)

Basically, under certain conditions I don't manage to pinpoint, when a user tries to edit a document inside Nextcloud with OnlyOffice, the app doesn't open OO, but does download the doc.

I checked Nc logs and OO logs, without success.
I'll ask users to try to pair and access their borwser config, js errors.

(I can't reproduce the issue myself).

I searched issues here without much success, and the Nextcloud forum as well. 

I'll document my findings here.

**Comment by Antipkin-A** [comment]
@pierreozoux, Hi
which version of nextcloud server and Onlyoffice plugin are you using?

**Comment by pierreozoux** [comment]
Arf, really sorry.

Nc 23.0.9 and OO 7.4.4.

**Comment by ImaCrea** [comment]
Hi, I just faced this issue at the moment. 

Nextcloud 23.0.9
OnlyOffice plugin 7.4.4
OnlyOffice server 6.4.2.6

I was clicking on an internal link and when the browser tab opened, it started to load NC interface but then it triggered a download of the file instead of opening the oo editor. I tried again and had the same behaviour 4 or 5 time in a row and then finally the editor opened and we were back to normal.

I managed to capture the console of the browser :
![Capture d’écran 2022-10-07 à 13 39 27](https://user-images.githubusercontent.com/764332/194545764-2b0be9d3-b7f6-4878-9cb4-2c3b277794e5.png)

![Capture d’écran 2022-10-07 à 13 39 35](https://user-images.githubusercontent.com/764332/194545788-9cee86b3-7555-4fe4-b184-070b05b4c184.png)

![Capture d’écran 2022-10-07 à 13 39 43](https://user-images.githubusercontent.com/764332/194545835-6874a10d-09e1-45b8-8e18-7fc59a141a3a.png)

**Comment by pierreozoux** [comment]
I saw another log:
```
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 3 globals.js:62:15
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment util.js:135:11
TypeError: OCA.Onlyoffice.setting.formats is undefined
    canDisplay share.js:123
    H Sidebar.vue:1
    vt VueJS
    H Sidebar.vue:1
    VueJS 7
vue.runtime.esm.js:1897:12
```

So it seems that oo tries to start but the app didn't finish to fully load.

**Comment by Antipkin-A** [comment]
@pierreozoux 
We are preparing new release of the onlyoffice connector for nc23 on the branch [nc-23](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/tree/feature/nc-23). Can you check workable of this branch for your installation? Does it solve the problem?

**Comment by pierreozoux** [comment]
Sorry, didn't see that my issue is a duplicate of https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/620

@Antipkin-A I asked my users if they are willing to test a beta of the app to test the fix, will wait their answer and see.

In the mean time, I will test on my main instance.

My pipeline to build Nextcloud image accepts apps from the Nc app store, there is a bit of work on my side to make it accept git with submodule, but I will do it to test it.

I can't reproduce it myslef, so it will be hard to tell if that fix it, but if nobody complains, then, it means it is fixed \o/

Thanks a lot, I'll close this issue in the mean time.

**Comment by pierreozoux** [comment]
@Antipkin-A users are happy with the branch nc-23, I saw you released yesterday, I'll apply this release then.

Thanks again a lot for your help!

Have a nice weekend!

**Comment by ImaCrea** [comment]
Thanks!
