### ISSUE TITLE
OnlyOffice doesn't keep connection for longer than ~1 day

### ISSUE THREAD

**Issue by FelixBuehler** [ONLYOFFICE/onlyoffice-nextcloud#876]
Hey everybody,

had a Nextcloud 26 with normal Web/PHP Installation for the past 5 years.

My OnlyOffice always ran in a docker image (:latest)

Now I switched my Nextcloud 27 also to docker, with redis. When I try to connect to OnlyOffice, everything works fine. But arounds once a day, it loses the connection and I have to click on "save" again, then it works.

I get a error in the nextcloud logs:
```Server error: `POST https://onlyoffice.domain.net/ConvertService.ashx` resulted in a `504 Gateway Time-out` response: <html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><c (truncated...)```

Although my onlyoffice.domain.net is available 24/7. It just started when I changed to docker.

Anyone has any idea whats the problem here?

**Comment by gituser334455** [comment]
Да такая проблема так же и у меня, использую nextcloud snap 27.0.2. Думал проблема в сервере OnlyOffice использовал "Community Document Server", но после установки собственного сервер OnlyOffice проблема осталась, приходиться раз в сутки заходить нажимать на сохранить. Видимо проблема началась после обновления nextcloud.

**Comment by DarkRPA** [comment]
I'm having the same problem, Never had any problem with Nextcloud and onlyoffice in the past years, but suddenly out of nowhere everyday it disconnects. I have some theories, but I will try downgrading since it seems it will be the most possible option to try.

**Comment by FelixBuehler** [comment]
@DarkRPA Let us know if it works. Still haven't found a reason or solution to this.

**Comment by DarkRPA** [comment]
So, I have test downgrading to 25.0, and it did not work, tried again at 27.1, and also didn't work. It seems to be a fault of the Onlyoffice Nextcloud app. Because, for some reason (And I might be wrong because I didn't read the documentation) a null is being passed when starting the background check.
![imagen](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/assets/75390328/43e70baf-87a1-407a-9758-67ee620c6375)

For now, I have disabled manually the line in charge of disabling Onlyoffice when an error occurs.

At `custom_apps/onlyoffice/lib/Cron/EditorsCheck.php` line 104
```php
//$this->config->SetSettingsError($error);
//$this->notifyAdmins();
```

I have not tested yet that this works, but it may.

**Comment by FelixBuehler** [comment]
I will test it too, although it's line 148/149 for me.

**Comment by DarkRPA** [comment]
I have some results, when the daily disconnect should have happened instead, by doing the method I posted except I did not comment the line that notifies the admins (so I can actually know if it did something) I was able to keep Onlyoffice working even tho the error was raised
![imagen](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/assets/75390328/c2070e02-0d1a-48cf-ab47-9c5a02942b66)

This solves my issue temporally because just forcing Onlyoffice to shut up entirely shouldn't be the best approach. If anyone finds a better way of fixing this, it would be great.

**Comment by FelixBuehler** [comment]
I can confirm, commenting out `$this->config->SetSettingsError($error);` will work. So it's not OnlyOffice getting disconnected, but another error. 
Any idea how to find the reason of this?

**Comment by SergeyKorneyev** [comment]
This is most likely related to the new background check functionality. Here's some context and our plans and recommendations for fixing it: https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/864#issuecomment-1743257243

**Comment by SergeyKorneyev** [comment]
The version that includes the fixes (7.9.2/8.2.2) has just been released. Please try updating the connector and check if that helps.

**Comment by FelixBuehler** [comment]
@SergeyKorneyev For me it seems like the fix did work. Thank you!

**Comment by DarkRPA** [comment]
For me it didn't work either, I just decided to stick to my workaround for now until a few updates passes

**Comment by rebootit** [comment]
Can't find the line "custom_apps/onlyoffice/lib/Cron/EditorsCheck.php" in my Nextcloud any idea why ?

**Comment by pierreozoux** [comment]
@rebootit https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/864#issuecomment-1790467676
