### ISSUE TITLE
After Upgrade to 9.1.2 from 9.0.0 error in log ""Could not find resource onlyoffice/js/desktop.js"

### ISSUE THREAD

**Issue by rchaconmolero** [ONLYOFFICE/onlyoffice-nextcloud#981]
Nextloud 28.0.4

After updating from 9.0.0 to 9.1.2 we get this message.

"app":"jsresourceloader","method":"GET","url":"/apps/dashboard/","message":"Could not find resource onlyoffice/js/desktop.js to load"

After uninstalling the app and reinstalling, - verifying that the nextcloud folder does not exist in app folder - this message continues to appear in nextloud.log
"

,"app":"jsresourceloader","method":"GET","url":"/apps/dashboard/","message":"Could not find resource onlyoffice/js/desktop.js to load

**Comment by rchaconmolero** [comment]
Workaround -> Revert to 9.0.0 manually. Any ideas?

**Comment by baltaner** [comment]
Hi,
same here with nextcloud 28.0.4 and onlyoffice 9.1.2 - we got a lot of this error-messages.
As a workaround I did the following:
In <nextcloud-url>/nextcloud/apps/onlyoffice/js I copied onlyoffice-desktop.js to desktop.js and onlyoffice-desktop.js.map to desktop.js.map
That stopped the error-messages

**Comment by davidschillerJKU** [comment]
@LinneyS 
The issue probably stems from [this](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/3e2f1686a90767bcdb3543a309f8b38c4c09888d/lib/Listeners/WidgetListener.php#L65) line.

Commit d20b985 removed the "onlyoffice-" prefix and that landed in version 9.1.0.

**Comment by arnowelzel** [comment]
JFTR: this problem does not occur here (OnlyOffice 9.1.2, Nextcloud 28.0.4). So it seems to be a bit harder to track down.

Just to be sure - maybe try the following:

Disable and remove OnlyOffice in Nextcloud.

Remove the backend URL in the app settings by applying the following SQL statement:

```
update oc_appconfig set configValue='' where appid='onlyoffice' and configKey='DocumentServerUrl';
```

Install OnlyOffice again.

Go to the administrative options of OnlyOffice and enter the URL of the backend again and save the options, so OnlyOffice will confirm that it can talk to the backend.

This way my upgrade from 9.0.0 to 9.1.2 worked fine.

**Comment by geoglis** [comment]
I tried the way mentioned by @arnowelzel. Unfortunately this did not help. I had to downgrade to version 9.0
Now it works again like a charme.

**Comment by Nordlead75** [comment]
I have the same problem

**Comment by davidschillerJKU** [comment]
@geoglis @Nordlead75 
Have you tried the following change on `lib/Listeners/WidgetListener.php`:
```
65c65
<             Util::addScript("onlyoffice", "desktop");
---
>             Util::addScript("onlyoffice", "onlyoffice-desktop");
```
This silenced the error for me. Alternatively you can rename the `desktop.js` file like baltaner did.

**Comment by igefa-awelzel** [comment]
> @geoglis @Nordlead75 Have you tried the following change on `lib/Listeners/WidgetListener.php`:
> 
> ```
> 65c65
> <             Util::addScript("onlyoffice", "desktop");
> ---
> >             Util::addScript("onlyoffice", "onlyoffice-desktop");
> ```
> 
> This silenced the error for me. Alternatively you can rename the `desktop.js` file like baltaner did.

That is strange - here OnlyOffice 9.1.2 works without that change, i.e. with `Util::addScript("onlyoffice", "desktop");`

No errors at all and everything works as expected, eventhough the script is named `js/onlyoffice-desktop.js` and not `js/desktop.js`.

But according to https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/js.html this should not work at all, since `Util::addScript()` will add a script for a given application which is expected to exist in the `js/` path with the given name. So maybe the WidgetListener is only used in specific situations. I just open end edit documents but disabled any kind of widgets in the files application, so maybe this is the reason, why I don't get any errors in the log?

**Comment by arnowelzel** [comment]
That is strange - here OnlyOffice 9.1.2 works without that change, i.e. with `Util::addScript("onlyoffice", "desktop");`

No errors at all and everything works as expected, eventhough the script is named `js/onlyoffice-desktop.js` and not `js/desktop.js`.

But according to https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/js.html this should not work at all, since `Util::addScript()` will add a script for a given application which is expected to exist in the `js/` path with the given name. So maybe the WidgetListener is only used in specific situations. I just open end edit documents but disabled any kind of widgets in the files application, so maybe this is the reason, why I don't get any errors in the log?

**Comment by Nordlead75** [comment]
Thanks a lot its done for me

**Comment by joskapista44** [comment]
I have the same issue. Everything is the latest stable.

**Comment by rchaconmolero** [comment]
I tried the way mentioned by @arnowelzel. Unfortunately this did not help.

**Comment by rchaconmolero** [comment]
Efectivamente, haciendo los cambios en lib/Listeners/Widgets Listener.php como indica davidschillerJKU o renombrando el fichero "onlyoffice-desktop.js" a "desktop.js" resuelve el problema. Esperaremos a que haya una solución definitiva antes de actualizar a 9.1.2

**Comment by HajasDS** [comment]
go to folder /path/to/nextcloud/apps/onlyoffice/js
Check if you see files beginning with onlyoffice-*
If you can see the files, run this:
`for file in onlyoffice-*; do
    # Check if the file actually exists to avoid errors
    if [[ -f "$file" ]]; then
        # Use parameter expansion to strip the prefix
        newname="${file#onlyoffice-}"
        mv "$file" "$newname"
        echo "Renamed '$file' to '$newname'"
    fi
done`
