### ISSUE TITLE
Widgets in 29.0.1 don't work properly

### ISSUE THREAD

**Issue by pschopen** [ONLYOFFICE/onlyoffice-nextcloud#994]
Nextcloud Server 29.0.0 introduced a new widget function. Office documents mentioned in talk chats will show a preview that can be added inside the configured office without leaving the talk app.

OnlyOffice imstwad only shows the edit bar without showing the document. It also hides the following talk messages underneath. The biggest problem is that OnlyOffice also locks the file in files_lock and doesn't unlock it after leaving the chat.

**Comment by Mer0me** [comment]
If you add manually a link to a onlyoffice document in a talk conversation, the preview is unusable (and useless) AND if you open the document in another tab, the user appears twice in the list of current connected users. Edition of the document may become impossible because 2 cursors are visible, and the letters you type go sometime behind one or the other.

If you share the document through the Talk share button, no preview and everything is fine.

**Comment by alexonlyoffice** [comment]
@Mer0me, @pschopen, thank you for the reports. we confirm that there is a problem related to the new widgets and we registered this behavior as a bug. we will update the issue as soon as it is solved.
